blueprint:
  name: Aziz
  description: >
    Creates an occupancy sensor that reports occupied while its input occupancy
    sensor is occupied, as long as it's dark outside, and remaining occupied
    while an input boolean is true.
  author: "Scott James Remnant <scott@netsplit.com>"
  domain: template
  input:
    occupancy:
      name: Occupancy
      description: >
        Occupancy sensor to monitor.
      selector:
        entity:
          filter:
            - domain: binary_sensor
    latch:
      name: Latch
      description: >
        The input that causes the sensor to remain occupied.
      selector:
        entity:
          filter:
            - domain: input_boolean

triggers:
  # Update with occupancy.
  - trigger: state
    entity_id: !input occupancy
    to:
      - "on"
      - "off"
  # Update when the weather changes.
  - trigger: state
    entity_id: binary_sensor.dark_outside
    to:
      - "on"
      - "off"
  # Update only when the latch is turned off.
  - trigger: state
    entity_id: !input latch
    to: "off"

variables:
  occupancy: !input occupancy
  latch: !input latch

binary_sensor:
  device_class: occupancy
  state: |
    {{ 'off' if (is_state(occupancy, 'off') or is_state('binary_sensor.dark_outside', 'off'))
       and is_state(latch, 'off') else 'on' }}
  attributes:
    entity_id: "{{ [ occupancy, 'binary_sensor.dark_outside', latch ] }}"
