blueprint:
  name: Mean Temperature
  description: >
    Creates a temperature sensor that provides the mean value of input
    temperature sensors.
  author: "Scott James Remnant <scott@netsplit.com>"
  domain: template
  input:
    sensors:
      name: Sensors
      description: >
        The mean value will be calculated from these sensors.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: temperature
          multiple: true

variables:
  sensors: !input sensors

sensor:
  device_class: temperature
  unit_of_measurement: "°F"
  state: |
    {% set values = (sensors
                     | expand
                     | selectattr('state', 'is_number')
                     | map(attribute='state')
                     | map('float')
                     | list) %}
    {{ (values | sum) / (values | count) }}
  state_class: measurement
  attributes:
    entity_id: "{{ sensors }}"
