blueprint:
  name: Light Switch
  description: >
    Synchronize lights and a switch so that the switch appears to directly
    control the lights; with the switch matching the state of the lights
    as if those are controlled directly.
  author: Scott James Remnant <scott@netsplit.com>
  domain: automation
  input:
    lights:
      name: Lights
      description: These lights will be synchronized with the switch.
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    switch:
      name: Switch
      description: This switch will be synchronized with the lights.
      selector:
        entity:
          filter:
            - domain: switch

mode: queued

triggers:
  - trigger: state
    entity_id: !input lights
    to:
      - "on"
      - "off"
    id: light
  - trigger: state
    entity_id: !input switch
    to:
      - "on"
      - "off"
    id: switch

variables:
  lights: !input lights
  switch: !input switch

actions:
  - choose:
      # When the light is the trigger, if the switch is not in the same state,
      # set it to the same state.
      - conditions:
          - condition: trigger
            id: light
          - "{{ not is_state(switch, trigger.to_state.state) }}"
        sequence:
          - action: |
              {% if trigger.to_state.state == 'on' %}
                switch.turn_on
              {% else %}
                switch.turn_off
              {% endif %}
            target:
              entity_id: !input switch

      # When the switch is the trigger, if no lights are in the same state,
      # set them to the same state.
      - conditions:
          - condition: trigger
            id: switch
          - "{{ lights | select('is_state', trigger.to_state.state) | list | length == 0 }}"
        sequence:
          - action: |
              {% if trigger.to_state.state == 'on' %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: !input lights
