blueprint:
  name: Light Switch
  description: >
    Synchronize lights and a switch so that the switch appears to directly
    control the lights; with the switch matching the state of the lights
    as if those are controlled directly.
  author: Scott James Remnant <scott@netsplit.com>
  domain: automation
  input:
    lights:
      name: Lights
      description: These lights will be synchronized with the switch.
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    switch:
      name: Switch
      description: This switch will be synchronized with the lights.
      selector:
        entity:
          filter:
            - domain: light

mode: queued

triggers:
  - trigger: state
    entity_id: !input lights
    to:
      - "on"
      - "off"
    id: light
  - trigger: state
    entity_id: !input switch
    to:
      - "on"
      - "off"
    id: switch

variables:
  lights: !input lights
  switch: !input switch

actions:
  - choose:
      # When a light is the trigger, turn on the switch if any are on, or turn
      # off the switch if all are off.
      - conditions:
          - condition: trigger
            id: light
          - condition: template
            value_template: |
              {% if trigger.to_state.state == 'on' %}
                {{ lights | select('is_state', 'on') | list | length > 0 }}
              {% else %}
                {{ lights | select('is_state', 'on') | list | length == 0 }}
              {% endif %}
        sequence:
          - action: |
              {% if trigger.to_state.state == 'on' %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: !input switch

      # When the switch is the trigger, turn on lights if none are on, or turn
      # off lights if any are on.
      - conditions:
          - condition: trigger
            id: switch
          - condition: template
            value_template: |
              {% if trigger.to_state.state == 'on' %}
                {{ lights | select('is_state', 'on') | list | length == 0 }}
              {% else %}
                {{ lights | select('is_state', 'on') | list | length > 0 }}
              {% endif %}
        sequence:
          - action: |
              {% if trigger.to_state.state == 'on' %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: !input lights
