blueprint:
  name: Occupancy Lights
  description: >
    Turn lights on and off based on room occupancy.
  author: Scott James Remnant <scott@netsplit.com>
  domain: automation
  input:
    lights:
      name: Lights
      description: These light will be turned on and off.
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    occupancy:
      name: Occupancy
      description: This sensor turns the lights on and off.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: occupancy
      default: null

mode: queued

triggers:
  - trigger: state
    entity_id: !input occupancy
    to:
      - "on"
      - "off"

actions:
  - if:
      - condition: state
        entity_id: !input occupancy
        state: "on"
    then:
      - action: light.turn_on
        target:
          entity_id: !input lights
    else:
      - action: light.turn_off
        target:
          entity_id: !input lights
