alias: Bedroom Blackout
id: bedroom_blackout
description: >
  Close the bedroom blackout blinds when we're sleeping in.

mode: queued

triggers:
  # Update blinds when we go to sleep.
  - trigger: state
    entity_id: binary_sensor.scotty_asleep
    to: "on"
  # Update blinds when the windows are closed.
  - trigger: state
    entity_id: binary_sensor.bedroom_window
    to: "off"
    for:
      seconds: 3

conditions:
  # Only when someone is sleeping.
  - condition: state
    entity_id: binary_sensor.scotty_asleep
    state: "on"
  # Only when the windows are closed.
  - condition: state
    entity_id: binary_sensor.bedroom_window
    state: "off"

actions:
  - choose:
      # Close blackout blinds when we go to sleep during the day.
      - conditions:
          - not:
              - condition: state
                entity_id: sensor.weather
                state: "night"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.bedroom_blackout

      # Close blackout blinds when we go to sleep with less than three hours
      # until sunrise.
      - conditions:
          # After sunset, not "night"; otherwise it matches if we go to bed
          # anytime before midnight since that's after sunrise that day.
          - condition: sun
            after: sunset
          - condition: sun
            after: sunrise
            after_offset: "-03:00:00"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.bedroom_blackout
