alias: Bedroom Switch
id: bedroom_switch
description: >
  Synchronize the bedroom switch with the lights so that the physical switch
  appears to directly control the lights; and with the switch matching the state
  of the lights if those are controlled directly.

mode: queued

triggers:
  - trigger: state
    entity_id: light.bedroom
    to:
      - "on"
      - "off"
    id: light
  - trigger: state
    entity_id: switch.bedroom
    to:
      - "on"
      - "off"
    id: switch

actions:
  - choose:
      # When the light is the trigger, if the switch is not in the same state,
      # set it to the same state.
      - conditions:
          - condition: trigger
            id: light
          - "{{ not is_state('switch.bedroom', states('light.bedroom')) }}"
        sequence:
          - action: |
              {% if is_state('light.bedroom', 'on') %}
                switch.turn_on
              {% else %}
                switch.turn_off
              {% endif %}
            target:
              entity_id: switch.bedroom

      # When the switch is the trigger, if the light is not in the same state,
      # set it to the same state.
      - conditions:
          - condition: trigger
            id: switch
          - "{{ not is_state('light.bedroom', states('switch.bedroom')) }}"
        sequence:
          - action: |
              {% if is_state('switch.bedroom', 'on') %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: light.bedroom
