alias: Dining Room Play
id: dining_room_play
description: >
  Set scenes while playing in the Dining Room.

mode: queued

triggers:
- trigger: state
  entity_id: input_boolean.dining_room_play
  to: null

actions:
  - choose:
    # Play time in the Dining Room.
    - conditions:
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'on'
      sequence:
        # Turn on the wall and beam lights, to get their current scene state;
        # wait a few seconds for it to take effect.
        - action: light.turn_on
          target:
            entity_id:
            - light.dining_room_beam
            - light.dining_room_south_left
            - light.dining_room_south_right
            - light.dining_room_west_left
            - light.dining_room_west_center
            - light.dining_room_west_right
        - delay:
            seconds: 3
        - action: scene.create
          data:
            scene_id: dining_room_play
            snapshot_entities:
            - light.dining_room_beam
            - light.dining_room_south_left
            - light.dining_room_south_right
            - light.dining_room_west_left
            - light.dining_room_west_center
            - light.dining_room_west_right

        # Now change the wall and beam lights scene.
        - action: scene.turn_on
          target:
            entity_id:
            - scene.dining_room_wall_play
            - scene.dining_room_beam_lights_play

    # Play time over.
    - conditions:
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        # Activate and then delete the saved lighting scene to restore the lights
        # to whatever they were before.
        - action: scene.turn_on
          target:
            entity_id: scene.dining_room_play
        - action: scene.delete
          target:
            entity_id: scene.dining_room_play
