alias: Dining Room Off
id: dining_room_off
description: >
  Turn things off when the last person goes to sleep, or the home is no longer
  occupied.

mode: single

triggers:
  # Turn things off when occupancy is no longer detected after the last person
  # leaves home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: "off"

  # Turn things off when we go to sleep.
  - trigger: state
    entity_id: binary_sensor.anyone_asleep
    to: "on"

  # Turn things off when we don't need privacy anymore.
  - trigger: state
    entity_id: input_boolean.dining_room_privacy
    to: "off"

conditions:
  - or:
      - condition: state
        entity_id: binary_sensor.anyone_home
        state: "off"
      - condition: state
        entity_id: binary_sensor.anyone_asleep
        state: "on"
  - condition: state
    entity_id: input_boolean.dining_room_privacy
    state: "off"

actions:
  - action: light.turn_off
    continue_on_error: true
    target:
      entity_id:
        - light.dining_room_chandelier
        - light.dining_room_spots

  - action: media_player.media_pause
    continue_on_error: true
    target:
      entity_id: media_player.dining_room
