alias: Dining Room Lights
id: dining_room_lights
description: >
  Turn the dining room lights on and off based on the home occupancy.

mode: queued

triggers:
  # Update lights based on the time of day and weather.
  - trigger: state
    entity_id: sensor.weather
    not_to: 'unavailable'
  # Update lights when we wake up or go to sleep.
  - trigger: state
    entity_id: binary_sensor.scotty_asleep
    to:
      - 'on'
      - 'off'
  # Update lights when the first person comes home, or the last person leaves
  # home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to:
      - 'on'
      - 'off'

actions:
  - choose:
    # Turn lights on at night.
    - conditions:
        - condition: state
          entity_id: sensor.weather
          state: 'night'
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.scotty_asleep
          state: 'off'
        # Only when someone is home.
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: 'on'
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights on during a cloudy day.
    - conditions:
        - condition: state
          entity_id: sensor.weather
          state: 'cloudy-day'
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.scotty_asleep
          state: 'off'
        # Only when someone is home.
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: 'on'
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights off when the sun comes out during the day to save on power.
    - conditions:
        - condition: state
          entity_id: sensor.weather
          state:
            - 'hot-day'
            - 'day'
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights off when someone is sleeping, or nobody is home.
    - conditions:
        - or:
            - condition: state
              entity_id: binary_sensor.scotty_asleep
              state: 'on'
            - condition: state
              entity_id: binary_sensor.anyone_home
              state: 'off'
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego
