alias: Dining Room Switch
id: dining_room_switch
description: >
  Synchronize the dining room switch with the lights so that the physical switch
  appears to directly control the lights; and with the switch matching the state
  of the lights if those are controlled directly.

mode: queued

triggers:
  - trigger: state
    entity_id: light.dining_room
    to:
      - "on"
      - "off"
    id: light
  - trigger: state
    entity_id: switch.dining_room
    to:
      - "on"
      - "off"
    id: switch

actions:
  - choose:
      # When the light is the trigger, if the switch is not in the same state,
      # set it to the same state.
      - conditions:
          - condition: trigger
            id: light
          - "{{ not is_state('switch.dining_room', states('light.dining_room')) }}"
        sequence:
          - action: |
              {% if is_state('light.dining_room', 'on') %}
                switch.turn_on
              {% else %}
                switch.turn_off
              {% endif %}
            target:
              entity_id: switch.dining_room

      # When the switch is the trigger, if the light is not in the same state,
      # set it to the same state.
      - conditions:
          - condition: trigger
            id: switch
          - "{{ not is_state('light.dining_room', states('switch.dining_room')) }}"
        sequence:
          - action: |
              {% if is_state('switch.dining_room', 'on') %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: light.dining_room
