alias: Dining Room Windows
id: dining_room_windows
description: >
  Open and close the dining room window blinds based on the time of day,
  sun position, and weather.

mode: queued

triggers:
  # Update blinds at sunset and sunrise.
  - trigger: state
    entity_id: sun.sun
    from: null
  # Trigger when sun shines through the dining room windows by reaching
  # 220° azimuth.
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: 220
  # Trigger in stages matching the three window panes based on the elevation
  # of the sun: 55° for the top pane, 45° for the middle pane, and 24° for the
  # lower pane.
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 55
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 45
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 24
  # Trigger once the sun is behind Potrero hill by reaching around 5.5°
  # elevation.
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 5.5
  # Update the blinds based on the weeather.
  - trigger: state
    entity_id: weather.home
    to: null
  # Update blinds when the windows are closed.
  - trigger: state
    entity_id: binary_sensor.dining_room_top_windows
    to: 'off'
    for:
      seconds: 3
    id: 'close'
  - trigger: state
    entity_id: binary_sensor.dining_room_bottom_windows
    to: 'off'
    for:
      seconds: 3
    id: 'close'
  # Update blinds when the TV turns on or off.
  - trigger: state
    entity_id: media_player.lg_webos_tv
    from: null
  # Update blinds when we're playing.
  - trigger: state
    entity_id: input_boolean.dining_room_play
    from: null
  - trigger: state
    entity_id: input_boolean.loft_play
    from: null

variables:
  cloudy_day: >
    {{ states('weather.home') not in
       ['clear-night', 'partlycloudy', 'sunny', 'windy' ]
    }}

actions:
  # Set the target blind state.
  - variables:
      target: none
  - choose:
    # Close the blinds when the sun is shining through the third pane and it's
    # not cloudy.
    - conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 220
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 5.5
          below: 24
        - "{{ not cloudy_day }}"
      sequence:
        - variables:
            target: 100

    # Close the blinds while we're playing in the dining room.
    - conditions:
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'on'
      sequence:
        - variables:
            target: 100

    # Partially close the blinds When the sun is shining through the second
    # pane and it's not cloudy.
    - conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 220
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 24
          below: 45
        - "{{ not cloudy_day }}"
      sequence:
        - variables:
            target: 66

    # Close the top of the blinds when the sun is shining through the first
    # pane and it's not cloudy.
    - conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 220
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 45
          below: 55
        - "{{ not cloudy_day }}"
      sequence:
        - variables:
            target: 33

    # Close the top of the blinds while we're playing in the loft.
    - conditions:
        - condition: state
          entity_id: input_boolean.loft_play
          state: 'on'
      sequence:
        - variables:
            target: 33

    # Close the top of the blinds during the day if the TV is on.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: state
          entity_id: media_player.lg_webos_tv
          state: 'on'
      sequence:
        - variables:
            target: 33

    # Open blinds during the day.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
      sequence:
        - variables:
            target: 0

    # Open blinds (night time scene) at night.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
      sequence:
        - variables:
            target: -1

  # Apply the target blind state, adjusted for whether windows are open or
  # closed.
  - choose:
    - conditions:
        - "{{ target >= 100 }}"
        - condition: state
          entity_id: binary_sensor.dining_room_top_windows
          state: 'off'
        - condition: state
          entity_id: binary_sensor.dining_room_bottom_windows
          state: 'off'
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.dining_room_windows_closed

    - conditions:
        - "{{ target >= 66 }}"
        - condition: state
          entity_id: binary_sensor.dining_room_top_windows
          state: 'off'
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.late_afternoon_sun

    - conditions:
        - "{{ target >= 33 }}"
        - condition: state
          entity_id: binary_sensor.dining_room_top_windows
          state: 'off'
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.afternoon_sun

    - conditions:
        - "{{ target >= 0 }}"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.dining_room_daytime

    - conditions:
        - "{{ target < 0 }}"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.dining_room_nighttime
