alias: Dining Room Tabletop
id: dining_room_tabletop
description: >
  Set dining room light scenes based on the tabletop TV.

mode: queued

triggers:
  # Trigger when the Tabletop TV changes state; and since we unplug it,
  # treat "unavailable" and "unknown" as "off".
  - trigger: state
    entity_id: media_player.dining_room_tabletop
    to: "on"
  - trigger: state
    entity_id: media_player.dining_room_tabletop
    to: "off"
    id: "tabletop_off"
    for:
      minutes: 15
  # Trigger when the sun sets.
  - trigger: state
    entity_id: sensor.weather
    to: "night"

actions:
  - choose:
      # If the TV turns on at night, or sunset happens when the TV is on,
      # use the lower light D&D scene.
      - conditions:
          - condition: state
            entity_id: media_player.dining_room_tabletop
            state: "on"
          - condition: state
            entity_id: sensor.weather
            state: "night"
        sequence:
          - action: script.dining_room_dnd

      # If the TV turns on, set the Game Setup scene.
      - conditions:
          - condition: state
            entity_id: media_player.dining_room_tabletop
            state: "on"
        sequence:
          - action: script.dining_room_game_setup

      # If the TV is turning off, game over.
      - conditions:
          - condition: trigger
            id: "tabletop_off"
        sequence:
          - action: script.dining_room_game_over
