alias: Dining Room Lights
id: dining_room_lights
description: >
  Turn the dining room lights on and off based on the home occupancy.

mode: queued

triggers:
  # Update lights at sunset and sunrise.
  - trigger: state
    entity_id: sun.sun
    to:
      - 'above_horizon'
      - 'below_horizon'
  # Update lights during the day based on the weather.
  - trigger: state
    entity_id: weather.home
    to: null
  # Update lights when we wake up or go to sleep.
  - trigger: state
    entity_id: binary_sensor.everyone_asleep
    to:
      - 'on'
      - 'off'
  # Update lights when the first person comes home, or the last person leaves
  # home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to:
      - 'on'
      - 'off'

variables:
  cloudy_day: >
    {{ states('weather.home') not in
       ['clear-night', 'partlycloudy', 'sunny', 'windy' ]
    }}

actions:
  - choose:
    # Turn lights on at night.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.everyone_asleep
          state: 'off'
        # Only when someone is home.
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: 'on'
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights on during a cloudy day.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - "{{ cloudy_day }}"
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.everyone_asleep
          state: 'off'
        # Only when someone is home.
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: 'on'
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights off when the sun comes out during the day to save on power.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - "{{ not cloudy_day }}"
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Turn lights off when someone is sleeping, or nobody is home.
    - conditions:
        - or:
            - condition: state
              entity_id: binary_sensor.everyone_asleep
              state: 'on'
            - condition: state
              entity_id: binary_sensor.anyone_home
              state: 'off'
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego
