alias: Gaming Power Limit
id: gaming_power_limit
description: >
  Limit "Vecna" GPU power, and reduce home power consumption, while both gaming
  PCs are on.

mode: queued

triggers:
  - trigger: state
    entity_id: binary_sensor.gaming_power_limit
    to:
      - "on"
      - "off"
  - trigger: state
    entity_id: sensor.vecna_lastsystemstatechange
    to: null

actions:
  - if:
      - condition: state
        entity_id: binary_sensor.gaming_power_limit
        state: "on"
    then:
      - action: button.press
        target:
          entity_id: button.vecna_power_limit_enable
      - action: switch.turn_off
        target:
          entity_id:
            - switch.office_wall_desk_right_switch_top
            - switch.loft_wall_south_switch_top
    else:
      - action: button.press
        target:
          entity_id: button.vecna_power_limit_disable
      - action: switch.turn_on
        target:
          entity_id:
            - switch.office_wall_desk_right_switch_top
            - switch.loft_wall_south_switch_top
