alias: Home Off
id: home_off
description: >
  Turn things off when the last person goes to sleep, or the home is no longer
  occupied.

mode: single

triggers:
  # Turn things off when occupancy is no longer detected after the last person
  # leaves home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: "off"

  # Turn things off when the last person goes to sleep.
  - trigger: state
    entity_id: binary_sensor.everyone_asleep
    to: "on"

actions:
  # Turn lights off that don't have their own automations triggered by the last
  # person leaving home.
  - action: light.turn_off
    target:
      area_id:
        - kitchen
        - downstairs_bathroom
        - bathroom
        - stairs
        - roof
      entity_id:
        - light.dining_room_chandelier
        - light.dining_room_spots
        - light.bedroom_left_closet
        - light.bedroom_right_closet

  # Stop any Sonos playing music.
  - action: media_player.media_stop
    target:
      entity_id:
        - media_player.dining_room
        - media_player.kitchen
        - media_player.office
        - media_player.bedroom
        - media_player.loft
        - media_player.bathroom
        - media_player.downstairs_bathroom

  # Turn off the TV.
  - action: media_player.turn_off
    target:
      entity_id:
        - media_player.lg_webos_tv
