alias: Kitchen Lights
id: kitchen_lights
description: >
  Turns on the kitchen counter lights for 15 minutes at night when anyone comes
  home, or for midnight snacks when there's motion in the dining room.

mode: restart

triggers:
  # Trigger using the Eve Motion, as it's the most reliable.
  - trigger: state
    entity_id: binary_sensor.dining_room_motion_occupancy
    to: 'on'
  # Trigger when the first person arrives home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: 'on'
  # Trigger when known people arrive home, even if the home is otherwise already
  # occupied.
  - trigger: zone
    entity_id:
      - person.scotty
      - person.shadie
    zone: zone.home
    event: enter

conditions:
  # Only at night.
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  # Only when the kitchen counter light is off, unless an instance of this
  # automation is running, which implies a restart check.
  - or:
    - condition: state
      entity_id: light.kitchen_counter
      state: 'off'
    - condition: state
      entity_id: automation.kitchen_lights
      attribute: current
      state: 1

actions:
  # Turn lights on at 25% brightness, unless already on.
  - if:
      - condition: state
        entity_id: light.kitchen_counter
        state: 'off'
    then:
      - action: light.turn_on
        data:
          brightness_pct: 25
        target:
          entity_id: light.kitchen_counter
      # Assume it takes a few seconds, avoid triggering our own wait condition.
      - delay:
          seconds: 3

  # Keep the light on for 15 minutes.
  # But if the kitchen counter state changes, assume we should leave it alone
  # and not turn it off in the middle of someone's burrito.
  - wait_for_trigger:
    - trigger: state
      entity_id: light.kitchen_counter
    timeout:
      minutes: 15
  - if:
      - "{{ not wait.completed }}"
    then:
      - action: light.turn_off
        target:
          entity_id: light.kitchen_counter
