alias: Kitchen Home at Night
id: kitchen_home_at_night
description: >
  Turns on the entrance lights when anyone comes home late at night.

mode: restart

triggers:
  # When the first person arrives home, turn on the lights.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: "on"
    not_from: "unavailable"
  # But also turn on the lights if known people arrive home, even if the home
  # is otherwise already occupied.
  - trigger: zone
    entity_id:
      - person.scotty
    zone: zone.home
    event: enter

conditions:
  # Only at night.
  - condition: state
    entity_id: sensor.weather
    state: "night"

actions:
  # Turn on the entrance light.
  - action: light.turn_on
    target:
      entity_id: light.entrance

  # Keep the entrance light on for 15 minutes.
  - delay:
      minutes: 15

  # Turn off the entrance light.
  - action: light.turn_off
    target:
      entity_id: light.entrance
