alias: Loft Switch
id: loft_switch
description: >
  Synchronize the loft switch with the lights so that the physical switch
  appears to directly control the lights; and with the switch matching the state
  of the lights if those are controlled directly.

mode: queued

triggers:
  - trigger: state
    entity_id: light.loft
    to: null
    id: light
  - trigger: state
    entity_id: light.loft_wall
    to: null
  - trigger: state
    entity_id: switch.loft
    to: null
    id: switch

variables:
  # When the TV is on, only the wall lights are controlled by the switch.
  light: |
    {% if is_state('media_player.lg_webos_tv', 'on') %}
      light.loft_wall
    {% else %}
      light.loft
    {% endif %}

actions:
  - choose:
    # When the light is the trigger, if the switch is not in the same state,
    # set it to the same state.
    - conditions:
        - condition: trigger
          id: light
        - "{{ not is_state('switch.loft', states(light)) }}"
      sequence:
        - action: |
            {% if is_state(light, 'on') %}
              switch.turn_on
            {% else %}
              switch.turn_off
            {% endif %}
          target:
            entity_id: switch.loft

    # When the switch is the trigger, if the light is not in the same state,
    # set it to the same state.
    - conditions:
        - condition: trigger
          id: switch
        - "{{ not is_state(light, states('switch.loft')) }}"
      sequence:
        - action: |
            {% if is_state('switch.loft', 'on') %}
              light.turn_on
            {% else %}
              light.turn_off
            {% endif %}
          target:
            entity_id: "{{ light }}"
