alias: Office Blinds
id: office_blinds
description: >
  Open and close the office window blinds based on the time of day.

mode: queued

triggers:
  # Update blinds at sunset and sunrise.
  - trigger: state
    entity_id: sensor.weather
    to: "night"
  - trigger: state
    entity_id: sensor.weather
    from: "night"
    not_to: "unavailable"
  # Update blinds when there is motion in the office.
  - trigger: state
    entity_id: binary_sensor.office_occupancy
    to: "on"
    id: "open"
  # Update blinds when the windows are closed.
  - trigger: state
    entity_id: binary_sensor.office_window
    to: "off"
    for:
      seconds: 3
    id: "close"

actions:
  - choose:
      # Open blinds during the day.
      - conditions:
          - not:
              - condition: state
                entity_id: sensor.weather
                state: "night"
          # Excluding triggers that should only close the windows.
          - not:
              - condition: trigger
                id: "close"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.office_daytime

      # Close blinds at night.
      - conditions:
          - condition: state
            entity_id: sensor.weather
            state: "night"
          # Only when the windows are closed.
          - condition: state
            entity_id: binary_sensor.office_window
            state: "off"
          # Excluding triggers that should only open the windows.
          - not:
              - condition: trigger
                id: "open"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.office_nighttime
