alias: Office Blinds
id: office_blinds
description: >
  Open and close the office window blinds based on the time of day.

mode: queued

triggers:
  # Update blinds at sunset and sunrise.
  - trigger: state
    entity_id: sensor.weather
    to: "night"
  - trigger: state
    entity_id: sensor.weather
    from: "night"
    not_to: "unavailable"
  # Update blinds when the windows are closed.
  - trigger: state
    entity_id: binary_sensor.office_window
    to: "off"
    for:
      seconds: 3

actions:
  - choose:
      # Open blinds during the day.
      - conditions:
          - not:
              - condition: state
                entity_id: sensor.weather
                state: "night"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.office_daytime

      # Close blinds at night.
      - conditions:
          - condition: state
            entity_id: sensor.weather
            state: "night"
          # Only when the windows are closed.
          - condition: state
            entity_id: binary_sensor.office_window
            state: "off"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.office_nighttime
